name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag socmon
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
            # The name of the image you would like to push
            name: socmon
            # The login username for the registry
            username: ${{ secrets.DOCKER_USERNAME_ACCESS }}
            # The login password for the registry
            password: ${{ secrets.DOCKER_PASSWORD_ACCESS }}
